#!/usr/bin/env python

import optparse
import sys

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input-data", dest="input_data", default="data-dev/comtrans-dev.g", help="Input file to tag")
optparser.add_option("-e", "--english-refs", dest="english_refs", default="data-dev/refs-dev.e", help="POS-tagged English refs")
optparser.add_option("-a", "--alignments", dest="alignments", default="data-dev/comtrans-dev.a", help="German-English alignment file")
(opts, _) = optparser.parse_args()

input_file = open(opts.input_data)
english_refs_file = open(opts.english_refs)
alignment_file = open(opts.alignments)


## YOUR CODE HERE ##


input_file.close()
english_refs_file.close()
alignment_file.close()
sys.stderr.write("Done\n")
