#!/usr/bin/env python

# File:         default
# Authors:      Casey Davis, Harry Okun, Brian Sladek, Ayla Taylor
# Description:  POS tagger that randomly assigns tags to each word.

import optparse
import random
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input-data", dest="input_data", default="data/test.f", help="Input file to tag")
(opts, _) = optparser.parse_args()

input_file = open(opts.input_data)
tags = ("ADJ", "ADP", "ADV", "AUX", "CONJ", "DET", "INTJ", "NOUN", "NUM",
        "PART", "PRON", "PROPN", "PUNCT", "SCONJ", "SYM", "VERB", "X")

sys.stderr.write("Tagging...\n")
for sentence in input_file.readlines():
    sentence = sentence.strip()
    tagged_sentence = ""
    for word in sentence.split(" "):
        tag = tags[random.randint(0, len(tags) - 1)] # randomly assign tag
        tagged_sentence += word + ":::" + tag + " "
    sys.stdout.write(tagged_sentence + "\n")

input_file.close()
sys.stderr.write("Done\n")
