#!/usr/bin/env python

# File:         file_chopper
# Author:       Casey Davis
# Description:  Used to grab a subset of lines from a file.

import sys
import optparse

optparser = optparse.OptionParser()
optparser.add_option("-f", "--file", dest="filename", help="Name of file to chop")
optparser.add_option("-b", "--begin-line", dest="begin", default="0", type="int", help="Line number to begin at (inclusive)")
optparser.add_option("-e", "--end-line", dest="end", type="int", help="Line number to end at (not inclusive)")
(opts, _) = optparser.parse_args()

if not opts.filename:
    optparser.error("File is required!")
if not opts.end:
    optparser.error("End line is required!")

f = open(opts.filename)
lines = f.readlines()
for line in lines[opts.begin:opts.end]:
    sys.stdout.write(line)

f.close()
